# Generated by Django 4.2.6 on 2023-11-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active_alter_verificationcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='is_verified',
            field=models.BooleanField(),
        ),
    ]
