# Generated by Django 4.2.6 on 2023-11-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_verificationcode_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
