services:
  store-app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./:/store_server
    environment:
      - DB_HOST=database
      - DB_NAME=store_server
      - DB_USER=admin
      - DB_PASS=qwertyasdfghzxcvbn

    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=store_server
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwertyasdfghzxcvbn

    