services:
  store-app:
    build:
      context: .
    ports:
      - '8000:8000'
    container_name: store-app
    volumes:
      - ./:/store_server
    environment:
      - DB_HOST=database
      - DB_NAME=store_server
      - DB_USER=admin
      - DB_PASS=qwertyasdfghzxcvbn

    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - ./:/store_server
    environment:
      - POSTGRES_DB=store_server
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwertyasdfghzxcvbn

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    container_name: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    container_name: worker
    volumes:
      - ./:/store_server
    links:
      - redis
    depends_on:
      - redis
      - database

    environment:
      - DB_HOST=database
      - DB_NAME=store_server
      - DB_USER=admin
      - DB_PASS=qwertyasdfghzxcvbn

  flower:
    build:
      context: .
    hostname: flower
    container_name: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./:/store_server
    links:
      - redis
    depends_on:
      - redis
    ports:
      - '5555:5555'